#!/bin/bash

server=$(grep -Ev "HostName|User|IdentityFile|ProxyJump|+ssh-rsa|+ssh-rsa" ~/.ssh/config 2> /dev/null | sed 's/\*//g' | awk '{print $2}' | awk /./ | sort -k 3 | fzf --layout=reverse)

file=$(ssh $server "find / -type f 2> /dev/null" | fzf --layout=reverse)

nvim scp://$server/$file
